server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name btc09.178.128.105.41.sslip.io 178.128.105.41 _;
    return 301 https://btc09.org$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name btc09.178.128.105.41.sslip.io;

    ssl_certificate /etc/letsencrypt/live/btc09.178.128.105.41.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/btc09.178.128.105.41.sslip.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://btc09.org$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name explorer.btc09.178.128.105.41.sslip.io;
    return 301 https://explorer.btc09.org$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name explorer.btc09.178.128.105.41.sslip.io;

    ssl_certificate /etc/letsencrypt/live/explorer.btc09.178.128.105.41.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/explorer.btc09.178.128.105.41.sslip.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://explorer.btc09.org$request_uri;
}
